### ISSUE TITLE
Documentation Build Fails Due to Broken Links

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/documentation#139]
```
12:03:41 PM: [en] Creating an optimized production build...
12:03:41 PM: [Local Search] [INFO]: The documentation is not versioned (/opt/build/repo/versions.json does not exist).
12:03:42 PM: [info] [webpackbar] Compiling Client
12:03:42 PM: [info] [webpackbar] Compiling Server
12:04:47 PM: [success] [webpackbar] Client: Compiled successfully in 1.07m
12:04:58 PM: [success] [webpackbar] Server: Compiled successfully in 1.26m
12:05:11 PM: [Local Search] [INFO]: Gathering documents
12:05:11 PM: [Local Search] [INFO]: Parsing documents
12:05:22 PM: [Local Search] [INFO]: Building index
12:05:23 PM: [Local Search] [INFO]: Writing index to disk
12:05:23 PM: [Local Search] [INFO]: Index written to disk, success!
12:05:23 PM: Unable to build website for locale "en".
12:05:23 PM: Error: Docusaurus found broken links!
12:05:23 PM:
12:05:23 PM: Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
12:05:23 PM: Exhaustive list of all broken links found:
12:05:23 PM:
12:05:23 PM: - On source page path = /docs/architecture/adr/adr_0009:
12:05:23 PM:  -> linking to (https://docs.securecodebox.io/docs/scanners/gitleaks) (resolved as: /docs/architecture/adr/(https://docs.securecodebox.io/docs/scanners/gitleaks))
12:05:23 PM:  -> linking to (https://github.com/returntocorp/semgrep) (resolved as: /docs/architecture/adr/(https://github.com/returntocorp/semgrep))
12:05:23 PM:  -> linking to (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) (resolved as: /docs/architecture/adr/(https://kubernetes.io/docs/concepts/workloads/pods/init-containers/))
12:05:23 PM:  -> linking to (https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container) (resolved as: /docs/architecture/adr/(https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/)
12:05:23 PM:
12:05:23 PM:  at Object.reportMessage (/opt/build/repo/node_modules/@docusaurus/utils/lib/index.js:357:19)
12:05:23 PM:  at Object.handleBrokenLinks (/opt/build/repo/node_modules/@docusaurus/core/lib/server/brokenLinks.js:142:17)
12:05:23 PM:  at async buildLocale (/opt/build/repo/node_modules/@docusaurus/core/lib/commands/build.js:160:5)
12:05:23 PM:  at async tryToBuildLocale (/opt/build/repo/node_modules/@docusaurus/core/lib/commands/build.js:32:20)
12:05:23 PM:  at async Object.mapAsyncSequencial (/opt/build/repo/node_modules/@docusaurus/utils/lib/index.js:312:24)
12:05:23 PM:  at async build (/opt/build/repo/node_modules/@docusaurus/core/lib/commands/build.js:68:25)
12:05:24 PM: npm ERR! code ELIFECYCLE
12:05:24 PM: npm ERR! errno 1
12:05:24 PM: npm ERR! securecodebox@2.0.0 build: `docusaurus build`
12:05:24 PM: npm ERR! Exit status 1
12:05:24 PM: npm ERR!
12:05:24 PM: npm ERR! Failed at the securecodebox@2.0.0 build script.
12:05:24 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:05:24 PM: npm ERR! A complete log of this run can be found in:
12:05:24 PM: npm ERR! /opt/buildhome/.npm/_logs/2021-10-18T10_05_24_086Z-debug.log
12:05:24 PM: 
12:05:24 PM: ────────────────────────────────────────────────────────────────
12:05:24 PM:  "build.command" failed 
12:05:24 PM: ────────────────────────────────────────────────────────────────
12:05:24 PM: 
12:05:24 PM: Error message
12:05:24 PM: Command failed with exit code 1: npm install; npm run build;
12:05:24 PM: 
12:05:24 PM: Error location
12:05:24 PM: In Build command from Netlify app:
12:05:24 PM: npm install; npm run build;
```

**Comment by Weltraumschaf** [comment]
Fixed in [main repo](https://github.com/secureCodeBox/secureCodeBox/pull/736).
